### ISSUE TITLE
Powerwall Firmware 22.18.6 Upgrade - Flashing Powerflow Animation

### ISSUE THREAD

**Issue by jasonacox** [jasonacox/pypowerwall#23]
The latest firmware upgrade from Tesla Powerwall has changed the powerflow animation javascript on the gateway.  JavaScript error are now being produced for anyone using the pypowerwall proxy to render the animation.

@danisla Let me know if you see the same thing or have any suggestions for a fix.  I'm taking a look as well.

Errors:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/836718/192803211-bda88c0c-bc4f-44ff-a7e0-1ade841c8480.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/836718/192803445-2be8c70b-a457-4591-89c0-46a4ceae815d.png">

<img width="455" alt="image" src="https://user-images.githubusercontent.com/836718/192802809-7877ff7b-a4d3-44ca-bae5-e9953a5ca8ef.png">

Issue also raised in Powerwall-Dashboard: https://github.com/jasonacox/Powerwall-Dashboard/issues/88

**Comment by danisla** [comment]
I was gonna say, this looks like a caching issue. We might be able to inject some no-cache headers to prevent it from breaking.

**Comment by jasonacox** [comment]
Thanks Dan!  Did you happen to see this on your dakboard displays? I suspect this is going to be a rare occurrence.  I'll see if there is something simple we can do.

**Comment by danisla** [comment]
My powerwalls are offline this week because I'm adding another one so I didn't see it when the firmware update went out. However, I did see this behavior a couple times when I was developing the dashboard and it was a caching issue.

I'll see what my dakboard does when my powerwalls come back online later this week.

**Comment by danisla** [comment]
So I'm still on 20.18.3. I have a first gen gateway. When I check for updated firmware, says I'm up-to-date. 

Is there something special I can do to get the newer firmware?

**Comment by jasonacox** [comment]
That's interesting! It doesn't seem like Tesla pushes out firmware versions globally. I suspect they have a digital twin of all of our configurations and only apply updates to those systems that need it, or at least the ones they want to "test" with.

**Comment by jasonacox** [comment]
Flashing animation due to firmware upgrade raised in https://github.com/jasonacox/Powerwall-Dashboard/discussions/112.  TODO: Research cause (browser or proxy cache) and solution (no-cache header and/or TTL).

**Comment by jasonacox** [comment]
So there are two issues it seems:

1) The animation and required assets are cached by the browser indefinitely, meaning that a refresh or reload won't fix it.
2) The pypowerwall proxy caches all the js, css and other assets indefinitely, same problem as above. The fix is to do a pypowerwall proxy restart. 

To fix the browser cache, I added the "Cache-Control: no-cache" header to the non-API endpoints (ie. animation css, js, etc). 

To fix the local cache, based on some observations from @mcbirse in the discussion https://github.com/jasonacox/Powerwall-Dashboard/discussions/112, I made changes to the proxy server to detect when Powerwall Authentication happens (ie. auth token will change during a Firmware update) and then force clear the local cache.  

This all seemed to work and I noticed the browser would re-request all the assets when a browser reload was performed (did not happened before).  I released [Build t20](https://hub.docker.com/r/jasonacox/pypowerwall/tags?page=1&name=t20) that contains this update (see [diff](https://github.com/jasonacox/pypowerwall/commit/76a2344ce63b3986af7028cf67fd813282b7a255?diff=unified)).

Now, I confess, I tend to over-engineer things. As I watched the debug log during my tests of t20, it occured to me that all the logic I added to provide a local cache was only being used on a browser reload.  That is a rare event for a dashboard especially if you are rendering an animation.  Removing the local cache removes the need to detect a firmware update.  I pulled that code and new logic out and released [Build t21](https://hub.docker.com/r/jasonacox/pypowerwall/tags?page=1&name=t21) (see [diff](https://github.com/jasonacox/pypowerwall/commit/efa8b20e8b37f475d5abc3eccb032428ab21d832)).  

I just need another Firmware upgrade to test this new code.  Sadly, a firmware upgrade on my system just happened last night before I made these changes so I won't be able to test this for a while but I'll publish this update so others can report how well it works during firmware updates on their systems.  I am going to continue to test the t21 code to ensure I didn't introduce any memory leaks before I update the "latest" tag (currently t19) with this new version (t21).

**Comment by jasonacox** [comment]
As part of testing t21, I had an idea. It would be nice to be able to display the Powerwall firmware version or other data using some simple JQ calls.  To support the CORS policy, the pypowerwall proxy also needs to set a "Access-Control-Allow-Origin: *" header.  I added that and updated the example.html to include firmware version information in [Build t22](https://hub.docker.com/r/jasonacox/pypowerwall/tags?page=1&name=t22) (see [diff](https://github.com/jasonacox/pypowerwall/commit/9f28291bc1becaac22830f25e1c23d2c8f7deb9a)):

<img width="574" alt="image" src="https://user-images.githubusercontent.com/836718/203648381-e961b2b9-b917-4d6d-8119-ae272de9e6f7.png">

**Comment by mcbirse** [comment]
Great solution to this issue! Look forward to testing this and providing feedback... whenever my next firmware update happens. Maybe it won't be too long for me as mine hasn't updated to 22.26.4 yet.

Adding the firmware version to the Power Flow animation is a really nice addition too - love it! ❤️

**Comment by jasonacox** [comment]
Thanks!  Hopefully you can be the first to test it! 😄  I pushed the Build t22 to "latest" if you want to upgrade now.

**Comment by mcbirse** [comment]
> Look forward to testing this and providing feedback... whenever my next firmware update happens.

[Confirmed](https://github.com/jasonacox/Powerwall-Dashboard/discussions/109#discussioncomment-5279692) no more issues with the Power Flow animation after a FW update for me. 👍

**Comment by jasonacox** [comment]
Thanks @mcbirse !  No issues for me either.  Thanks everyone! 🙏
