### ISSUE TITLE
Possible FleetAPI bug in __main__.py

### ISSUE THREAD

**Issue by darroni** [jasonacox/pypowerwall#93]
The latest pypowerwall (0.9) appears to have a bug in the #Get Powerwall Mode section.  When running in Cloud Mode with no FleetAPI configured, pypowerwall returns an exception on line 152:
```
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/darroni/myenv/lib/python3.12/site-packages/pypowerwall/__main__.py", line 152
    'site_id': pw.client.fleet.site_id
               ^^^^^^^^^^^^^^^^^^^^^^^
```
It looks like it's trying to force the site.id to the fleet.site_id.  I simply changed the variable to None, per your documentation and it solved the problem.

![image](https://github.com/jasonacox/pypowerwall/assets/17322676/49bb0fb8-687b-4471-9924-f6177567e562)

**Comment by jasonacox** [comment]
Great find @darroni ! It also uncovered another bug. Thank you. I'll push out a patch.

**Comment by jasonacox** [comment]
jasonacox/pypowerwall:0.9.1t57-beta
